create extension if not exists pgcrypto;

create table if not exists public.codenames_words (
  id bigint generated always as identity primary key,
  word text not null unique,
  category text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  room_code text not null unique,
  grid_size integer not null check (grid_size between 4 and 6),
  blue_count integer not null check (blue_count > 0),
  red_count integer not null check (red_count > 0),
  assassin_count integer not null check (assassin_count > 0),
  current_team text not null check (current_team in ('red', 'blue')),
  status text not null default 'active' check (status in ('active', 'finished')),
  winner text check (winner in ('red', 'blue')),
  red_remaining integer not null check (red_remaining >= 0),
  blue_remaining integer not null check (blue_remaining >= 0),
  cards_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.game_messages (
  id bigint generated always as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  player_name text not null,
  message text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists game_messages_game_id_created_at_idx
  on public.game_messages (game_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row
execute procedure public.set_updated_at();

insert into public.codenames_words (word, category)
values
  ('APPLE', 'food'),
  ('BANANA', 'food'),
  ('ORANGE', 'food'),
  ('GRAPE', 'food'),
  ('PEAR', 'food'),
  ('PEACH', 'food'),
  ('PLUM', 'food'),
  ('CHERRY', 'food'),
  ('MELON', 'food'),
  ('LEMON', 'food'),
  ('CARROT', 'food'),
  ('POTATO', 'food'),
  ('ONION', 'food'),
  ('GARLIC', 'food'),
  ('PEPPER', 'food'),
  ('TOMATO', 'food'),
  ('BREAD', 'food'),
  ('CHEESE', 'food'),
  ('BUTTER', 'food'),
  ('MILK', 'food'),
  ('PASTA', 'food'),
  ('SOUP', 'food'),
  ('PIZZA', 'food'),
  ('BURGER', 'food'),
  ('COOKIE', 'food'),
  ('CAKE', 'food'),
  ('HONEY', 'food'),
  ('COFFEE', 'food'),
  ('TEA', 'food'),
  ('RIVER', 'nature'),
  ('LAKE', 'nature'),
  ('OCEAN', 'nature'),
  ('SEA', 'nature'),
  ('STREAM', 'nature'),
  ('MOUNTAIN', 'nature'),
  ('VALLEY', 'nature'),
  ('DESERT', 'nature'),
  ('FOREST', 'nature'),
  ('JUNGLE', 'nature'),
  ('ISLAND', 'nature'),
  ('VOLCANO', 'nature'),
  ('CAVE', 'nature'),
  ('BEACH', 'nature'),
  ('COAST', 'nature'),
  ('SKY', 'nature'),
  ('CLOUD', 'nature'),
  ('RAIN', 'nature'),
  ('SNOW', 'nature'),
  ('STORM', 'nature'),
  ('LIGHTNING', 'nature'),
  ('WIND', 'nature'),
  ('SUN', 'nature'),
  ('MOON', 'nature'),
  ('STAR', 'nature'),
  ('PLANET', 'nature'),
  ('COMET', 'nature'),
  ('GALAXY', 'nature'),
  ('SPACE', 'nature'),
  ('HOUSE', 'place'),
  ('CABIN', 'place'),
  ('CASTLE', 'place'),
  ('TOWER', 'place'),
  ('BRIDGE', 'place'),
  ('ROAD', 'place'),
  ('STREET', 'place'),
  ('SCHOOL', 'place'),
  ('LIBRARY', 'place'),
  ('MUSEUM', 'place'),
  ('THEATER', 'place'),
  ('STADIUM', 'place'),
  ('PARK', 'place'),
  ('GARDEN', 'place'),
  ('MARKET', 'place'),
  ('HOSPITAL', 'place'),
  ('OFFICE', 'place'),
  ('FACTORY', 'place'),
  ('AIRPORT', 'place'),
  ('STATION', 'place'),
  ('HOTEL', 'place'),
  ('TABLE', 'object'),
  ('CHAIR', 'object'),
  ('SOFA', 'object'),
  ('BED', 'object'),
  ('PILLOW', 'object'),
  ('LAMP', 'object'),
  ('MIRROR', 'object'),
  ('WINDOW', 'object'),
  ('DOOR', 'object'),
  ('BOTTLE', 'object'),
  ('CUP', 'object'),
  ('PLATE', 'object'),
  ('BOWL', 'object'),
  ('SPOON', 'object'),
  ('FORK', 'object'),
  ('KNIFE', 'object'),
  ('CLOCK', 'object'),
  ('RADIO', 'object'),
  ('CAMERA', 'object'),
  ('PHONE', 'object'),
  ('COMPUTER', 'object'),
  ('KEYBOARD', 'object'),
  ('SCREEN', 'object'),
  ('PRINTER', 'object'),
  ('ROBOT', 'object'),
  ('ENGINE', 'object'),
  ('BATTERY', 'object'),
  ('CABLE', 'object'),
  ('CAR', 'travel'),
  ('TRUCK', 'travel'),
  ('BUS', 'travel'),
  ('TRAIN', 'travel'),
  ('BICYCLE', 'travel'),
  ('MOTORCYCLE', 'travel'),
  ('AIRPLANE', 'travel'),
  ('HELICOPTER', 'travel'),
  ('BOAT', 'travel'),
  ('SHIP', 'travel'),
  ('ROCKET', 'travel'),
  ('ANCHOR', 'travel'),
  ('COMPASS', 'travel'),
  ('MAP', 'travel'),
  ('TICKET', 'travel'),
  ('DOG', 'animal'),
  ('CAT', 'animal'),
  ('HORSE', 'animal'),
  ('COW', 'animal'),
  ('SHEEP', 'animal'),
  ('RABBIT', 'animal'),
  ('BEAR', 'animal'),
  ('LION', 'animal'),
  ('TIGER', 'animal'),
  ('WOLF', 'animal'),
  ('FOX', 'animal'),
  ('MONKEY', 'animal'),
  ('ELEPHANT', 'animal'),
  ('ZEBRA', 'animal'),
  ('GIRAFFE', 'animal'),
  ('PANDA', 'animal'),
  ('KOALA', 'animal'),
  ('KANGAROO', 'animal'),
  ('DOLPHIN', 'animal'),
  ('WHALE', 'animal'),
  ('SHARK', 'animal'),
  ('TURTLE', 'animal'),
  ('FROG', 'animal'),
  ('SNAKE', 'animal'),
  ('EAGLE', 'animal'),
  ('OWL', 'animal'),
  ('PENGUIN', 'animal'),
  ('DUCK', 'animal'),
  ('GOOSE', 'animal'),
  ('ARTIST', 'people'),
  ('DOCTOR', 'people'),
  ('NURSE', 'people'),
  ('TEACHER', 'people'),
  ('LAWYER', 'people'),
  ('PILOT', 'people'),
  ('SAILOR', 'people'),
  ('FARMER', 'people'),
  ('BAKER', 'people'),
  ('CHEF', 'people'),
  ('DANCER', 'people'),
  ('SINGER', 'people'),
  ('ACTOR', 'people'),
  ('WRITER', 'people'),
  ('PAINTER', 'people'),
  ('SCIENTIST', 'people'),
  ('ENGINEER', 'people'),
  ('MECHANIC', 'people'),
  ('FIREFIGHTER', 'people'),
  ('POLICE', 'people'),
  ('SOLDIER', 'people'),
  ('COACH', 'people'),
  ('STUDENT', 'people'),
  ('LEADER', 'people'),
  ('KING', 'people'),
  ('QUEEN', 'people'),
  ('KNIGHT', 'people'),
  ('WIZARD', 'people'),
  ('PIRATE', 'people'),
  ('NINJA', 'people'),
  ('BOOK', 'culture'),
  ('NOVEL', 'culture'),
  ('POEM', 'culture'),
  ('LETTER', 'culture'),
  ('PAPER', 'culture'),
  ('PENCIL', 'culture'),
  ('PEN', 'culture'),
  ('NOTEBOOK', 'culture'),
  ('SCISSORS', 'culture'),
  ('GLUE', 'culture'),
  ('PAINT', 'culture'),
  ('BRUSH', 'culture'),
  ('CANVAS', 'culture'),
  ('GUITAR', 'culture'),
  ('PIANO', 'culture'),
  ('DRUM', 'culture'),
  ('VIOLIN', 'culture'),
  ('TRUMPET', 'culture'),
  ('SONG', 'culture'),
  ('MELODY', 'culture'),
  ('DANCE', 'culture'),
  ('GAME', 'culture'),
  ('PUZZLE', 'culture'),
  ('CARD', 'culture'),
  ('DICE', 'culture'),
  ('TROPHY', 'culture'),
  ('FLAG', 'symbol'),
  ('CROWN', 'symbol'),
  ('SWORD', 'symbol'),
  ('SHIELD', 'symbol'),
  ('HAMMER', 'symbol'),
  ('LADDER', 'symbol'),
  ('FLOWER', 'nature'),
  ('TREE', 'nature'),
  ('ROOT', 'nature'),
  ('LEAF', 'nature'),
  ('STONE', 'nature'),
  ('ROCK', 'nature'),
  ('SAND', 'nature'),
  ('GOLD', 'material'),
  ('SILVER', 'material'),
  ('IRON', 'material'),
  ('DIAMOND', 'material'),
  ('PEARL', 'material'),
  ('RUBY', 'material'),
  ('EMERALD', 'material'),
  ('HEART', 'abstract'),
  ('BRAIN', 'abstract'),
  ('VOICE', 'abstract'),
  ('SMILE', 'abstract'),
  ('DREAM', 'abstract'),
  ('IDEA', 'abstract'),
  ('MEMORY', 'abstract'),
  ('HOPE', 'abstract'),
  ('LUCK', 'abstract'),
  ('COURAGE', 'abstract'),
  ('PEACE', 'abstract'),
  ('TRUTH', 'abstract'),
  ('JUSTICE', 'abstract'),
  ('POWER', 'abstract'),
  ('MAGIC', 'abstract'),
  ('FIRE', 'abstract'),
  ('ICE', 'abstract'),
  ('SHADOW', 'abstract'),
  ('LIGHT', 'abstract'),
  ('SPARK', 'abstract')
on conflict (word) do update
set
  category = excluded.category,
  is_active = true;
